---
- name: Build WAR file
  hosts: TomcatServers
  gather_facts: false
  tasks:
    - name: Copy WAR file
      git:
        repo: https://github.com/Vivich007/Web3.git
        dest: /home/centos/Web3/
        version: master  # or specify a branch or tag
      when: ansible_os_family == 'Redhat'

    - name: Copy WAR file
      git:
        repo: https://github.com/Vivich007/Web3.git
        dest: /home/centos/Web3/
        version: master 
      when: ansible_os_family == 'Debian'

    - name: Run Maven build
      shell: |
        cd /home/centos/Web3/
        mvn clean package
      when: ansible_os_family == 'Redhat'
    
    - name: Run Maven build
      shell: |
        cd /home/ubuntu/Web3
        mvn clean package
      when: ansible_os_family == 'Debian'
...